dist: jammy
sudo: false
language: cpp

before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y lcov
script:
  - cmake -H. -Bbuild
  - cmake --build build --config Debug --target coverage -j2
after_success:
  - bash <(curl -s https://codecov.io/bash)